#!/usr/bin/env python3
import distro
import os
from colorama import Fore
import getpass
import psutil
import uptime

def dfetch():
    print("___________________")
    try:
        print(Fore.BLUE + "User: " + os.environ['USER'] + Fore.RESET)
    except:
        print(Fore.BLUE + "User: " + getpass.getuser() + Fore.RESET)
    try:
        print(Fore.RED + "Shell: " + os.environ['SHELL'] + Fore.RESET)
    except :
        pass
    try:
        print(Fore.YELLOW + "Wm: " + os.environ['XDG_CURRENT_DESKTOP'] + " " + os.environ['DESKTOP_SESSION'] + Fore.RESET)
    except :
        pass
    try:
         print(Fore.GREEN + "Distro: " + distro.linux_distribution()[0] + Fore.RESET)
    except :
        pass
    try:
        print(Fore.CYAN + "Language: " + os.environ['LANGUAGE'] + Fore.RESET)
    except:
        pass
    try:
        print(Fore.LIGHTWHITE_EX + "Terminal: " +os.environ["TERM"])
    except :
        pass
    try:
        pid = os.getpid()
        py = psutil.Process(pid)
        mem = psutil.virtual_memory()
        ram = round(mem.total / 1048576)
        print(Fore.LIGHTRED_EX + "Ram: " + str(ram) + Fore.RESET)

    except :
        pass
        
    try:
        timeeelinux = uptime._boottime_linux()
        print(Fore.LIGHTBLUE_EX + "Uptime: "+ str(timeeelinux) + Fore.RESET)
    except :
        pass
    print("‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
dfetch()